version: "3.2"
services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
  api:
    image: node:12.14
    container_name: challange-encurtador-backend
    restart: always
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - .env
    entrypoint: ["/bin/bash", "./start.sh"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
