version: "3.2"
services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_challenge_encurtador
  api:
    image: node:12.14
    container_name: challange-encurtador-backend
    restart: always
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    env_file:
      - .env
    command: yarn start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
